version: '3.8'

services:
  document_management:
    build: 
      context: ./services/document_management
    container_name: document_management_service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCUMENT_MANAGEMENT_PORT=${DOCUMENT_MANAGEMENT_PORT}
    ports:
      - "${DOCUMENT_MANAGEMENT_PORT}:${DOCUMENT_MANAGEMENT_PORT}"
    depends_on:
      - chroma_db
    volumes:
      - ./services/document_management/app/data:/app/data
    develop:
      watch:
        - action: sync
          path: ./services/document_management/app
          target: /app
          ignore:
            - __pychache__
            - "*.pyc"
        - action: rebuild
          path: ./services/document_management/requirements.txt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DOCUMENT_MANAGEMENT_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  chroma_db:
    build:
      context: ./services/chroma_db
    container_name: chroma_db_service
    environment:
      - CHROMA_DB_PORT=${CHROMA_DB_PORT}
    ports:
      - "%{CHROMA_DB_PORT}:8000"
    volumes:
      - ./services/chroma_db/data:/data

volumes:
  chromadb_data:
